DjangoProject/ClassBasedView(CBV)/cbv/cbv/urls.py
from django.contrib import admin
from django.urls import path
from cbv_app import views
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('cbv_app/', include('cbv_app.urls',namespace='cbv_app'))
]

DjangoProject/ClassBasedView(CBV)/cbv/cbv_app/urls.py
from django.urls import path, re_path
from cbv_app import views

app_name = 'cbv_app'

urlpatterns = [
    path('',views.HomeListView.as_view(),name='list'),
    re_path(r'^(?P<pk>[-\w]+)/$', views.HomeDetailView.as_view(),name='detail')
]

DjangoProject/ClassBasedView(CBV)/cbv/cbv_app/models.py
from django.db import models

# Create your models here.
class Home(models.Model):
    name = models.CharField(max_length=256)
    location = models.CharField(max_length=256)
    owner = models.CharField(max_length=256)

    def __str__(self):
        return self.name

class Members(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    home = models.ForeignKey(Home,
                            related_name='members',
                            on_delete = models.CASCADE)

    def __str__(self):
        return self.name

DjangoProject/ClassBasedView(CBV)/cbv/cbv_app/views.py
from django.shortcuts import render
from django.views.generic import View
from django.views.generic import TemplateView, ListView, DetailView
from cbv_app import models

# Create your views here.
class IndexView(TemplateView):
    template_name='index.html'

class HomeListView(ListView):
    model = models.Home #(returns context as home_list)

class HomeDetailView(DetailView):
    model = models.Home #(returns context as home)
    template_name = 'cbv_app/home_detail.html'

DjangoProject/ClassBasedView(CBV)/cbv/cbv_app/templates/cbv_app/cbv_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>BASE</title>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'cbv_app:list' %}">Home</a>
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'admin:index' %}">Admin<span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="#"></a>
          </div>
      </nav>
      <div class="jumbotron">
      {% block body_block %}
      {% endblock %}
      </div>
    </div>
  </body>
</html>

DjangoProject/ClassBasedView(CBV)/cbv/cbv_app/templates/cbv_app/home_detail.html
{% extends "cbv_app/cbv_app_base.html" %}
{% block body_block %}

<h1>welcome to Home detail view</h1>
<h2>Details:</h2>
<p>Home Info: {{ home.name }}</p>
<p>Location: {{ home.location }}</p>
<p>Owner: {{ home.owner }}</p>

<h3>Members:</h3>
{% for member in home.members.all %}
  <p>{{ member.name }} is {{ member.age }} years old</p>
{% endfor %}

{% endblock %}

DjangoProject/ClassBasedView(CBV)/cbv/cbv_app/templates/cbv_app/home_list.html
{% extends "cbv_app/cbv_app_base.html" %}
{% block body_block %}

<h1>Welcome to List View</h1>
<ol>
  {% for home in home_list %}
  <h3><li><a href="{{ home.id }}">{{ home.name }}</a></li></h3>
  {% endfor %}
</ol>

{% endblock %}

DjangoProject/ClassBasedView(CBV)/cbv/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>BASE</title>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'cbv_app:list' %}">Home</a>
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'admin:index' %}">Admin<span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="#"></a>
          </div>
      </nav>
      <div class="jumbotron">
      {% block body_block %}
      {% endblock %}
      </div>
    </div>
  </body>
</html>

DjangoProject/ClassBasedView(CBV)/cbv/templates/index.html
{% extends "base.html" %}
{% block body_block %}
  <h1> BASIC HOME PAGE</h1>
{% endblock %}