DjangoProject/Blog_project/mysite/blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('new/', views.UserCreation.as_view(), name='new'),
    path('thankyou/', views.ThankYou.as_view(), name='thankyou'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

DjangoProject/Blog_project/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import Index

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

DjangoProject/Blog_project/mysite/blog/models.py
from django.db import models

DjangoProject/Blog_project/mysite/blog/views.py
from django.contrib.auth import authenticate,login,logout
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import View,TemplateView,CreateView,ListView,DetailView,UpdateView,DeleteView
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
class Index(TemplateView):
    template_name = 'blog/index.html'

class Register(TemplateView):
    template_name = 'register.html'

class UserCreation(CreateView):
    form_class = UserCreationForm
    fiels = ('username', 'password')
    template_name = 'new.html'

    def get_success_url(self):
        return reverse('blog:thankyou')

    # def form_valid(self, form):
    #     return super(UserCreation,self).form_valid(form)

class ThankYou(TemplateView):
    template_name = 'thankyou.html'

class Login(TemplateView):
    template_name = 'login.html'

    def post(self,request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active")
        else:
            return HttpResponse("Invalid Credentials")

class Logout(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('index'))

DjangoProject/Blog_project/mysite/blog/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <title>Welcome to Blog</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Blogger</a>
    </nav>
      <marquee><h3 class="display-5">Welcome to BLOGGER!!!</h3></marquee>
      <div class="container">
        <div class="jumbotron">
          {% block body_block %}
          {% endblock %}
        </div>
      </div>
    </body>
</html>

DjangoProject/Blog_project/mysite/blog/templates/login.html
{% extends "base.html" %}
{% block body_block %}

<h2>Login:</h2>
<form action="{% url 'blog:login' %}" method="post">
  {% csrf_token %}

  <label for="username">Username:</label>
  <input type="text" name="username" placeholder="Enter username"><br>

  <label for="password">Password:</label>
  <input type="password" name="password" placeholder="password"><br>

  <br><input class="btn btn-info" type="submit" name="" value="Login">
</form>

{% endblock %}

DjangoProject/Blog_project/mysite/blog/templates/logout.html
{% extends "base.html" %}
{% block body_block %}

<h2>Your session has been logged out</h2>

{% endblock %}

DjangoProject/Blog_project/mysite/blog/templates/new.html
{% extends "base.html" %}
{% block body_block %}
<h4>Register here:</h4>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button class="btn btn-primary" type="submit">SignUp</button>
  <!-- <a href="{% url 'blog:thankyou' %}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">SignUp</a> -->
</form>

{% endblock %}

DjangoProject/Blog_project/mysite/blog/templates/register.html
{% extends "base.html" %}
{% block body_block %}
  <h4>Continue for Registration</h4>
  <a href="{% url 'blog:new' %}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Continue</a>
{% endblock %}

DjangoProject/Blog_project/mysite/blog/templates/thankyou.html
{% extends "base.html" %}
{% block body_block %}

<h2>Thank you for Signing Up!</h2>
<br>
<h4>Click below to Login</h4>
<a href="{% url 'index' %}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Return</a>

{% endblock %}

DjangoProject/Blog_project/mysite/templates/blog/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <title>Welcome to Blog</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Blogger</a>
    </nav>
      <marquee><h3 class="display-5">Welcome to BLOGGER!!!</h3></marquee>
      {% block body_block %}
      {% endblock %}
    </body>
</html>

DjangoProject/Blog_project/mysite/templates/blog/index.html
{% extends "blog/base.html" %}
{% block body_block %}
<br><br>
<div class="btn-group-vertical">
    <a href="{% url 'admin:index' %}"><button type="button" class="btn btn-info">Admin</button></a><br>
  {% if user.is_authenticated %}
    <a href="{% url 'blog:logout' %}"><button type="button" class="btn btn-warning">Logout</button></a>
  {% else %}
    <a href="{% url 'blog:login' %}"><button type="button" class="btn btn-info">Login</button></a>
    <a href="{% url 'blog:register' %}"><button type="button" class="btn btn-info">Register</button></a><br>
  {% endif %}
</div>

{% endblock %}